Util.cpp: fix build error due to usage of libpng internals
with the update to png 1.4 some structs were made private and new
accessor functions added.

../Util.cpp: In function 'bool utilWritePNGFile(const char*, int, int, u8*)':
../Util.cpp:90:20: error: invalid use of incomplete type 'png_struct {aka struct png_struct_def}'
In file included from ../Util.cpp:25:0:
/include/libpng15/png.h:869:16: error: forward declaration of 'png_struct {aka struct png_struct_def}'