Util.cpp: fix build error due to wrong zlib function pointer prototype
../Util.cpp: In function 'gzFile_s* utilGzOpen(const char*, const char*)':
../Util.cpp:995:73: error: invalid conversion from 'int (*)(void*, void*, unsigned int)'
to 'int (*)(gzFile, voidp, unsigned int) {aka int (*)(gzFile_s*, void*, unsigned int)}' [-fpermissive]