remove conflicting glibc getopt header
the header was copied from an old glibc version for some reason
which conflicts with the modern posix conformant version in
the libc include dir.

In file included from TestEmu.cpp:35:0:
../getopt.h:115:20: error: declaration of C function 'int getopt()' conflicts with
In file included from /usr/include/zconf.h:452:0,
                 from /usr/include/zlib.h:34,
                 from ../unzip.h:68,
                 from ../System.h:23,
                 from ../GBA.h:23,
                 from TestEmu.cpp:28:
/usr/include/unistd.h:124:5: error: previous declaration 'int getopt(int, char* const*, const char*)' here